- platform: hp_ilo
  host: 192.168.0.5
  username: !secret ilo_username
  password: !secret ilo_password
  monitored_variables:
    - name: CPU fanspeed
      sensor_type: server_health
      unit_of_measurement: '%'
      value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
    - name: Inlet temperature
      sensor_type: server_health
      unit_of_measurement: 'C'
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: CPU temperature
      sensor_type: server_health
      unit_of_measurement:  'C'
      value_template: '{{ ilo_data.temperature["02-CPU"].currentreading[0] }}'


- platform: speedtest
  minute:
    - 10
    - 20
    - 30
    - 40
    - 50
  server_id: 1208
  monitored_conditions:
    - ping
    - download
    - upload

- platform: google_travel_time
  name: Daniel to home
  api_key: !secret google_maps_key
  origin: device_tracker.iphonedaniel
  destination: zone.home
- platform: google_travel_time
  name: Judith to home
  api_key: !secret google_maps_key
  origin: device_tracker.iphone_van_judith
  destination: zone.home
- platform: google_travel_time
  name: Daniel to Work
  api_key: !secret google_maps_key
  origin: device_tracker.iphonedaniel
  destination: !secret work_daniel
- platform: google_travel_time
  name: Judith to work
  api_key: !secret google_maps_key
  origin: device_tracker.iphone_van_judith
  destination: !secret work_judith



- platform: wunderground
  api_key: !secret wu_key
  lang: NL
  monitored_conditions:
    - alerts
    - feelslike_c
    - temp_c
    - weather
    - weather_1d_metric
    - weather_2d_metric
    - weather_3d_metric
    - weather_4d_metric
    - pressure_mb



#- platform: dsmr
#  host: 192.168.0.4
#  dsmr_version: 5



- platform: template
  sensors:
    voordeur_battery:
      friendly_name: "Voordeur Batterij"
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001ab3fb8.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001ab3fb8
    tuindeuren_battery:
      friendly_name: "Tuindeuren Batterij"
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001dbcd47.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001dbcd47
    tuindeur_battery:
      friendly_name: "Tuindeur Batterij"
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001e44e61.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001e44e61
    keukenraam_battery:
      friendly_name: "Keukenraam Batterij"
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001e4548d.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001e4548d
    dakterras_battery:
      friendly_name: "Dakterras Batterij"
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001dacff3.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: binary_sensor.door_window_sensor_158d0001dacff3
    badkamer_battery:
      friendly_name: "Badkamer Batterij"
      value_template: "{{ states.sensor.temperature_158d00019d34bb.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: sensor.temperature_158d00019d34bb
    ikea_ab_battery:
      friendly_name: "Ikea ab Batterij"
      value_template: "{{ states.sensor.tradfri_remote_control.attributes.battery_level }}"
      unit_of_measurement: '%'
      entity_id: sensor.tradfri_remote_control
