

###################################################
## Light level low and sunset switch on lights @home
###################################################

- alias: 'Light level is Low evening - Switch On'


  trigger:
    - platform: state
      entity_id: binary_sensor.low_lux
      to: 'on'
      for:
        minutes: 2
    - platform: sun
      event: sunset
      offset: '-1:00:00'

  condition:
    condition: and
    conditions:
      - condition: time
        after: "14:00:00"
      - condition: state
        entity_id: group.familie
        state: 'home'
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - group.woonkamer
        - light.overloop
    - service: switch.turn_on
      entity_id:
        - switch.gang_lamp

###################################################
## few lights on when not @home
###################################################

- alias: 'Light on not home'

  trigger:
    - platform: state
      entity_id: binary_sensor.low_lux
      to: 'on'
      for:
        minutes: 2
    - platform: sun
      event: sunset
      offset: '-1:00:00'

  condition:
    condition: and
    conditions:
      - condition: time
        after: "14:00:00"
      - condition: state
        entity_id: group.familie
        state: 'not_home'
  action:
    - service: light.turn_on
      entity_id:
        - light.dressoir
        - light.overloop
    - service: switch.turn_on
      entity_id:
        - switch.gang_lamp


###################################################
## Lights on entering home
###################################################

- alias: 'Lights on entering home'

  trigger:
    - platform: state
      entity_id: group.familie
      to: 'home'

  condition:
    condition: and
    conditions:
      - condition: time
        after: "14:00:00"
      - condition: state
        entity_id: binary_sensor.low_lux
        state: 'on'
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'


  action:
    - service: light.turn_on
      entity_id:
        - group.woonkamer
        - light.overloop
    - service: switch.turn_on
      entity_id:
        - switch.gang_lamp

###################################################
## Light level High switch off lights
###################################################


- alias: 'Light level is High - Switch Off'


  trigger:
    - platform: state
      entity_id: binary_sensor.high_lux
      to: 'on'
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: time
        after: "07:00:00"
        before: "15:00:00"

  action:
    - service: light.turn_off
      entity_id:
        - group.woonkamer
        - light.overloop
    - service: switch.turn_off
      entity_id:
        - switch.gang_lamp



###################################################
## Turn on/off Lights garden @night
###################################################


- alias: 'Tuin licht aan in de avond'

  trigger:
    - platform: sun
      event: sunset
      offset: '0:30:00'

  action:
    - service: switch.turn_on
      entity_id:
        switch.buitenlamp_schuur

- alias: 'Tuin licht uit in de nacht'

  trigger:
    - platform: time
      at: '0:20:00'

  action:
    - service: switch.turn_off
      entity_id:
        switch.buitenlamp_schuur
