- alias: 'Deurbel'
  trigger:
    - platform: mqtt
      topic: home/deurbel/state
      payload: "on"
  condition:
    - condition: state
      entity_id: input_boolean.block_deurbel
      state: 'off'
  action:
    - service: notify.telegram
      data:
        message: 'Er staat iemand aan de deur'
        data:
          photo:
            - url: http://192.168.0.18/axis-cgi/jpg/image.cgi?resolution=320x240
              caption: Bel - Voordeur
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomimac1
        ringtone_id: 10
        ringtone_vol: 25


- alias: Turn on block doorbel when starting
  trigger:
  - platform: homeassistant
    event: start
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.block_deurbel
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: input_boolean.block_deurbel
