
- alias: 'switch Nest @home'
  trigger:
    - platform: state
      entity_id: group.familie
      to: 'home'
  action:
    - service: script.turn_on
      entity_id:
        - script.set_nest_home

- alias: 'switch Nest Away'
  trigger:
    - platform: state
      entity_id: group.familie
      to: 'not_home'
  action:
    - service: script.turn_on
      entity_id:
        - script.set_nest_away
