#####################################################
##Telegram reply , IN PROGRESS!!
#####################################################
- alias: 'Telegram reply with Status'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/status'
  action:
    - service: notify.telegram
      data_template:
        message: ' System is online!


      Currently the tracker group is {{states.group.all_devices.state}}.

      Living room lights are {{states.group.livingroom_lights.state}}.

      Boys room lights are {{states.group.bedroom_two_lights.state}}.

      Master bedroom lights are {{states.group.master_bedroom_lights.state}}.


      The weather at home is currently {{states.sensor.dark_sky_hourly_summary.state}}


      Status Dakterras {{ states("binary_sensor.door_window_sensor_158d0001dacff3") }}

      Status Keukenraam {{ states("binary_sensor.door_window_sensor_158d0001e4548d") }}

      Status Tuindeuren deuren {{ states("binary_sensor.door_window_sensor_158d0001dbcd47") }}

      Status Tuindeur {{ states("binary_sensor.door_window_sensor_158d0001e44e61") }}

      Status Voordeur {{ states("binary_sensor.door_window_sensor_158d0001ab3fb8") }}'
